### ISSUE TITLE
torrc: Add AccountingMax so users aren't charged for unlimited bandwidth

### ISSUE THREAD

**Issue by elimisteve** [micahflee/tor-relay-bootstrap#17]
I added these lines to my torrc to ensure that no more than 2 TB/month of transfer is used (64GB is a bit less than 2 TB divided by 31 days):

```
AccountingMax 64 GB
AccountingStart day 00:00
```

Perhaps something similar should be added to the default torrc?  Hard to say what that should be considering that a certain amount of data transfer is free for certain hosting providers, like Digital Ocean, Vultr, Atlantic.net, and others...

**Comment by micahflee** [comment]
This is a good idea. Do you want to make a pull request that adds these two lines to the torrc, but commented out (since everyone's hosting environment is different)? Then add post-install instructions to bootstrap.sh that explains why you might want to uncomment them?

**Comment by elimisteve** [comment]
@micahflee Sounds good. Started doing this here: https://github.com/micahflee/tor-relay-bootstrap/pull/18
